{
  "workbench.colorTheme": "Snazzy Operator",
  "editor.fontFamily": "Operator Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontSize": 16,
  "editor.lineHeight": 25,
  "editor.letterSpacing": 0.5,
  "workbench.editor.tabSizing": "shrink",
  "html.format.enable": true,
  "html.format.preserveNewLines": true,
  "files.trimTrailingWhitespace": true,
  "editor.fontWeight": "400",
  "editor.cursorStyle": "line",
  "editor.cursorWidth": 2,
  "editor.cursorBlinking": "solid",
  "editor.renderWhitespace": "all",
  "editor.multiCursorModifier": "ctrlCmd",
  "workbench.startupEditor": "newUntitledFile",
  "editor.tabSize": 2,
  "terminal.integrated.fontFamily": "Operator Mono, Inconsolata for Powerline, monospace",
  "terminal.integrated.fontSize": 16,
  "window.zoomLevel": -0.4,
  "workbench.iconTheme": "vscode-icons",
  "workbench.activityBar.visible": true,
  "workbench.sideBar.location": "left",
  "editor.minimap.showSlider": "always",
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "window.title": "${dirty} ${activeEditorMedium}${separator}${rootName}",
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": false
  },
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "sync.gist": "{SECRET_KEY}",
  "sync.quietSync": false,
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "sync.autoDownload": true,
  "sync.autoUpload": true,
  "sync.forceDownload": false,
}
